"""inicial

Revision ID: ee2dd811eba5
Revises: 
Create Date: 2026-09-17 02:06:11.478256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'ee2dd811eba5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('amiga', 'mentora', 'grupo', name='tipochat', native_enum=False), nullable=False),
    sa.Column('otro_nombre', sa.String(length=120), nullable=False),
    sa.Column('otro_iniciales', sa.String(length=4), nullable=False),
    sa.Column('otro_tono', sa.Enum('rosa', 'lavanda', 'salvia', 'durazno', 'cielo', name='tono', native_enum=False), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('empresas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('iniciales', sa.String(length=4), nullable=False),
    sa.Column('tono', sa.Enum('rosa', 'lavanda', 'salvia', 'durazno', 'cielo', name='tono', native_enum=False), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('eventos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=160), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('hora', sa.String(length=5), nullable=False),
    sa.Column('duracion_min', sa.Integer(), nullable=False),
    sa.Column('modalidad', sa.Enum('virtual', 'presencial', name='eventomodalidad', native_enum=False), nullable=False),
    sa.Column('lugar', sa.String(length=120), nullable=False),
    sa.Column('descripcion', sa.String(length=400), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('modulos',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=120), nullable=False),
    sa.Column('corto', sa.String(length=60), nullable=False),
    sa.Column('descripcion', sa.String(length=240), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=False),
    sa.Column('ciudad', sa.String(length=80), nullable=False),
    sa.Column('ocupacion', sa.String(length=160), nullable=False),
    sa.Column('hijos', sa.Integer(), nullable=False),
    sa.Column('busca_empleo', sa.Enum('si', 'no', 'nose', name='buscaempleo', native_enum=False), nullable=False),
    sa.Column('eventos', sa.Enum('virtual', 'presencial', 'ambos', name='preferenciaeventos', native_enum=False), nullable=False),
    sa.Column('tono', sa.Enum('rosa', 'lavanda', 'salvia', 'durazno', 'cielo', name='tono', native_enum=False), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_table('chat_participantes',
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('no_leidos', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('chat_id', 'usuario_id')
    )
    op.create_table('empleos',
    sa.Column('id', sa.String(length=60), nullable=False),
    sa.Column('puesto', sa.String(length=160), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('ciudad', sa.String(length=80), nullable=False),
    sa.Column('jornada', sa.Enum('Tiempo completo', 'Medio tiempo', name='jornada', native_enum=False), nullable=False),
    sa.Column('modalidad', sa.Enum('Presencial', 'Remoto', 'Híbrido', name='empleomodalidad', native_enum=False), nullable=False),
    sa.Column('publicado_por_id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=1000), nullable=False),
    sa.Column('requisitos', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('coincidencias', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['publicado_por_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inscripciones',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('evento_id', sa.Integer(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['evento_id'], ['eventos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('usuario_id', 'evento_id')
    )
    op.create_table('mensajes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('texto', sa.String(length=1000), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('metas',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('objetivos', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('minutos_al_dia', sa.Integer(), nullable=False),
    sa.Column('horizonte_meses', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('usuario_id')
    )
    op.create_table('progreso_retos',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('modulo_id', sa.String(length=40), nullable=False),
    sa.Column('dia_actual', sa.Integer(), nullable=False),
    sa.Column('racha', sa.Integer(), nullable=False),
    sa.Column('completado_hoy', sa.Boolean(), nullable=False),
    sa.Column('reflexion_hoy', sa.String(length=2000), nullable=False),
    sa.Column('puntos', sa.Integer(), nullable=False),
    sa.Column('actualizado_en', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.ForeignKeyConstraint(['modulo_id'], ['modulos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('usuario_id')
    )
    op.create_table('publicaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('autor_id', sa.Integer(), nullable=False),
    sa.Column('etiqueta', sa.String(length=60), nullable=False),
    sa.Column('texto', sa.String(length=2000), nullable=False),
    sa.Column('foto_descripcion', sa.String(length=200), nullable=True),
    sa.Column('foto_escena', sa.Enum('actividad', 'estudio', name='fotoescena', native_enum=False), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['autor_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tareas_modulo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('modulo_id', sa.String(length=40), nullable=False),
    sa.Column('dia', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=160), nullable=False),
    sa.Column('frase', sa.String(length=240), nullable=False),
    sa.Column('duracion_seg', sa.Integer(), nullable=False),
    sa.Column('minutos', sa.Integer(), nullable=False),
    sa.Column('puntos', sa.Integer(), nullable=False),
    sa.Column('texto', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('consigna', sa.String(length=240), nullable=False),
    sa.ForeignKeyConstraint(['modulo_id'], ['modulos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('modulo_id', 'dia', name='uq_tarea_modulo_dia')
    )
    op.create_table('comentarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('publicacion_id', sa.Integer(), nullable=False),
    sa.Column('autor_id', sa.Integer(), nullable=False),
    sa.Column('texto', sa.String(length=500), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['autor_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['publicacion_id'], ['publicaciones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('empleos_guardados',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('empleo_id', sa.String(length=60), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['empleo_id'], ['empleos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('usuario_id', 'empleo_id')
    )
    op.create_table('likes',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('publicacion_id', sa.Integer(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['publicacion_id'], ['publicaciones.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('usuario_id', 'publicacion_id')
    )
    op.create_table('postulaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('empleo_id', sa.String(length=60), nullable=False),
    sa.Column('cv_nombre_archivo', sa.String(length=200), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['empleo_id'], ['empleos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id', 'empleo_id', name='uq_postulacion_usuario_empleo')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('postulaciones')
    op.drop_table('likes')
    op.drop_table('empleos_guardados')
    op.drop_table('comentarios')
    op.drop_table('tareas_modulo')
    op.drop_table('publicaciones')
    op.drop_table('progreso_retos')
    op.drop_table('metas')
    op.drop_table('mensajes')
    op.drop_table('inscripciones')
    op.drop_table('empleos')
    op.drop_table('chat_participantes')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_table('modulos')
    op.drop_table('eventos')
    op.drop_table('empresas')
    op.drop_table('chats')
    # ### end Alembic commands ###
